# cloudbuild.yaml - 修复版本
steps:
  # 步骤1：配置 Docker 认证
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'auth'
      - 'configure-docker'
      - 'asia-east1-docker.pkg.dev'
    id: 'docker-auth'

  # 步骤2：构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'docker-build'
    waitFor: ['docker-auth']
  
  # 步骤3：推送到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:$COMMIT_SHA'
    id: 'docker-push'
    waitFor: ['docker-build']

  # 步骤4：部署到 Cloud Run（修复参数格式）
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cui-red-green21'
      - '--image'
      - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1000m'
      - '--timeout=300'
      - '--concurrency=80'
      - '--max-instances=100'
      - '--project'
      - 'daytrader-dev-services-le2m'

    id: 'deploy'
    waitFor: ['docker-push']

      # 新增步骤：设置公开访问权限
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'cui-red-green21'
      - '--region=asia-east1'
      - '--project=daytrader-dev-services-le2m'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
    id: 'set-public-access'
    waitFor: ['deploy']

# 镜像标签
images:
  - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:$COMMIT_SHA'
  - 'asia-east1-docker.pkg.dev/daytrader-dev-security-tj0n/test-cui/cui-red-green:latest'

# 超时设置
timeout: 1800s

# 日志选项
options:
  logging: CLOUD_LOGGING_ONLY
