# clouddeploy.yaml - 修复版本
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cui-test-red-green-pipeline
description: "CUI Red-Green 应用部署流水线"
  annotations:
    # 指定使用现有存储桶
    clouddeploy.google.com/storage-bucket: "daytrader-build-e429-cloud-deploy-staging"
serialPipeline:
  stages:
    - targetId: cui-test  # 改为 cui-test
      profiles: []
    - targetId: cui-production  # 改为 cui-production
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cui-test
description: "测试环境"
run:
  location: projects/daytrader-dev-services-le2m/locations/asia-east1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cui-production
description: "生产环境"
run:
  location: projects/daytrader-dev-services-le2m/locations/asia-east1
requireApproval: true
